### ISSUE TITLE
DrJava at GMU: merge to GitHub

### ISSUE THREAD

**Issue by kauffman77** [DrJavaAtRice/drjava#7]
Hi DrJava Folks,

We have been using DrJava for a while at George Mason University and during the last couple years when there was not much activity on Source Forge, I downloaded the source and made some bug fixes and minor improvements for our students described here:
https://cs.gmu.edu/~kauffman/drjava/

I attempted to get some of these changes into the main branch by reporting the bug and the fix here:
https://sourceforge.net/p/drjava/bugs/955/

I would like to merge these changes into the main source and continue contributing. I have a student worker who is analyzing how to get Java 1.8 syntax support in the Interaction Pane and proper scaling/resolution on high DPI monitors.

My general approach will be to fork the repo and start some feature branches. When we have code that is ready I will issue a pull request on it.  If you folks would prefer a different approach please let me know.

Thanks for the great tool and I'm glad to see that DrJava hasn't been abandoned.
Cheers,
Chris

**Comment by ponderosaTX** [comment]
Hi Chris,

I am still becoming accustomed to github and just saw your message (after 10 months!).  My apologies.  I still monitor requests for support at SourceForge and generally respond to them within a few days.  A ten month response time is ghastly.  Moreover, you have made explicit suggestions on how to update the source, which never appear in SourceForge support requests. This semester I have a Ph.D. graduate student, Vu Phan (vhp1@rice.edu) working with me on maintaining DrJava; he will look at your patches very carefully and determine which ones should be incorporated in the current build (which has slightly evolved since January).  Thanks for you interest and support!

**Comment by kauffman77** [comment]
Thanks for responding, Corky.  I am happy to help as I find DrJava to be a great tool for introductory programming.  I have also made some progress on my fork of DrJava since a while back but git is supposedly good for such merging. I am happy to help and will attempt to make sure to update my repo in the near future to account for the current code I am using.
